### ISSUE TITLE
Crash when receiving message

### ISSUE THREAD

**Issue by ghost** [TheKeeperOfPie/Reader#4] opened 2015-08-04 13:35 UTC
When I have a new message, ie someone replied to a comment I've made, the application crashes. If I clear app data and relogin I can read the messages and then the application continues to work fine until I get a new message.

This happens only in 1.2, in previous versions I have recieved messages without a problem.
If it is of any concern I always disable the background checking of messages.

Please ask for any additional information I can provide.

**Comment by TheKeeperOfPie** [comment] 2015-08-05 14:53
Hi bendersteed. Yes, I've actually caught this bug yesterday morning, but between job interviewing and packing up my development equipment for a trip, I have not had the time to push a patch for this.

I appreciate your proactiveness in reporting this issue, and I hope to have this fixed once I have everything set back up. It is caused by a null error when parsing the messages list, and I will determine the root cause and get a fix out as soon as I can.

**Closed as completed** 2015-08-05 23:19 UTC

**Comment by TheKeeperOfPie** [comment] 2015-08-05 23:23
A build has been pushed to the Play Store fixing this issue, hopefully.
